### ISSUE TITLE
issue with lds_messages module

### ISSUE THREAD

**Issue by mnouri62** [mattjj/pylds#15] opened 2017-05-16 22:27 UTC
it seems lds_messages module doesn't work properly:
(I have the similar issue with importing other models from pylds as well)

>>> from pylds.models import DefaultDLS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mo/pylds/pylds/models.py", line 10, in <module>
    from pylds.states import LDSStates, LDSStatesZeroInflatedCountData, LaplaceApproxPoissonLDSStates
  File "/home/mo/pylds/pylds/states.py", line 8, in <module>
    from pylds.lds_messages_interface import info_E_step, info_sample, kalman_info_filter, kalman_filter, E_step
  File "/home/mo/pylds/pylds/lds_messages_interface.py", line 10, in <module>
    from pylds.lds_messages import \
ImportError: No module named lds_messages

**Comment by MrMallIronmaker** [comment] 2017-05-24 22:36
I've got this bug as well. I'm running Python 2.7 on Ubuntu 16.04, if that's useful information.

**Comment by mattjj** [comment] 2017-05-24 22:51
How are you installing the code?

**Comment by mnouri62** [comment] 2017-05-24 23:04
I believe the issue was my system couldn't recognize .pyx files: 
I renamed "lds_messages.pyx" to "lds_messages.py" and could overcome the error but the better way would be installation of cython and cimport and that should resolve this issue as well

**Comment by mattjj** [comment] 2017-05-24 23:23
When you install from github, you need cython, and by running the setup.py script in any of the standard ways will build the .pyx files into .c files and then invoke a C/C++ compiler to produce .so object files. The final extension module that is imported by CPython is named lds_messages.so (at least on POSIX platforms).

When you install from pip rather than github, the .c files are included in the distribution, and so the setup.py build process does not call cython and will only perform the latter step: that is, the setup process compiles the .c files into .so files.

If the lds_messages.so file isn't present, leading to the 'no module named' error, that means the build process failed. If you are installing from github, that could mean either the cython build or the C/C++ build failed (or that you didn't run the setup script at all). If you are installing via pip, that would mean the C/C++ build failed.

Our setup.py file would print a warning when the build fails in either of those cases, but it's easy to miss that warning message when a bunch of other stuff gets printed out. We're going to make it fail more obviously so that build errors can be easily noticed.

**Comment by mattjj** [comment] 2017-05-24 23:35
It looks like the pip install wasn't including the right source files (because it was looking for .cpp files while we were building the cython to .c files). We can reproduce the problem on travis, hopefully a fix is coming soon...

**Comment by mattjj** [comment] 2017-05-25 00:09
Also the glob rule for finding extension modules was broken; I always forget that glob doesn't support recursive expansion with `**`.

This isn't an issue if you (1) have cython installed and (2) install from github using `pip install -e .`, i.e. the "developer mode" setup. That's why this install process seemed to work for some people (me included) while the pip install was totally broken.

Updated setup.py coming soon to pypi...

**Comment by mattjj** [comment] 2017-05-25 01:35
Okay, I uploaded a new version to pypi (and updated master several times). Can you give it a shot, either using `pip install pylds` or installing from the github repo, and report back?

**Comment by MrMallIronmaker** [comment] 2017-05-25 04:59
Works for me, installed through `sudo -H pip install pylds`. I'm pretty sure I don't have Cython on my system. Thanks!

**Comment by mattjj** [comment] 2017-05-25 14:43
Awesome! Thanks for reporting this issue and bearing with us. I'll close the issue, but reopen it if the same problem appears again.

**Closed by mattjj** 2017-05-25 14:43 UTC

**Comment by mnouri62** [comment] 2017-05-25 17:44
Thanks for looking into the issues. I checked on Linux and mac (I installed using git clone and pip) and it all installs and works fine. The issue with polygamma is resolved as well.
